### PR TITLE
Add key-value pair type to list type to pass custom data

### PR DESCRIPTION
**Pull request by bombillazo**

### CODE REVIEW

**Comment by bombillazo** [comment]
Hey @fateh999 , I'd like to contribute to this repo

**Comment by fateh999** [comment]
Hi @bombillazo , Thanks for your pull request but i think this should be optional type. I am however working on a rewrite on this module so will try to incorporate this change soon.

**Comment by bombillazo** [comment]
That's great to hear!

I agree it should be optional. Indexes of the form [key: string] can be considered as being always optional so that would cover it. It'll be nice to have while we wait on the updated version. 

Glad to help any way I can.

**Comment by fateh999** [comment]
Hi, would you like to work on the rewrite of the library currently it is
suffering from lot of issues, due to no maintenance. I would like to
connect with you on Discord  [ fateh999#5219 ] or Skype
[ live:fateh.farooqui9 ]

**Pull request closed without merging**
